CC  = gcc
CXX = g++
LINK = g++
INCLUDE = -I/home/answermj/programs/boost/boost_1_52_0
#LIBS = -ws2_32 -lib/libboost_filesystem-mgw47-mt-1_52.a -lib/libboost_system-mgw47-mt-1_52.a
LIBS = -lpthread lib/libboost_filesystem.a lib/libboost_system.a
CFLAGS =
CXXFLAG = -Wall -fexceptions
MAKELIB = ar crv
MAKE = make
.PHONY: clean cleanall

export <CC CXX LINK INCLUDE CFLAGS CXXFLAGS MAKELIB MAKE>

APP = Util
OBJS = main.o libutil.a

$(APP): $(OBJS)
	$(LINK) -o $(APP) $(OBJS) $(LIBS)

main.o: main.cpp util/thread.hpp util/base.hpp util/base/base.hpp \
 util/base/memory.hpp util/base/in.hpp util/base/out.hpp \
 util/base/baseclass.hpp util/base/lexicalcast.hpp util/file.hpp \
 util/iterator.hpp util/collection.hpp util/cmdline.hpp util/string.hpp
	$(CXX) $(INCLUDE) $(CXXFLAGS) -c main.cpp
libutil.a: 
	$(MAKE) -C ./util


clean:
	rm $(OBJS)
	$(MAKE) -C ./util clean
cleanall:
	rm $(OBJS) $(APP)
	$(MAKE) -C ./util cleanall
